name: s_error_widget
description: A customizable error widget with support for headers, exception visualization, and retry actions.
issue_tracker: https://github.com/SoundSliced/s_error_widget/issues
repository: https://github.com/SoundSliced/s_error_widget
version: 2.1.0
homepage: https://github.com/SoundSliced/s_error_widget

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  s_packages: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
